# Generated by Django 5.0.1 on 2024-02-14 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Novels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="未知", max_length=255)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("author", models.CharField(default="未知", max_length=255)),
                ("word_count", models.IntegerField(default=0)),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "first_update_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_update_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("primary_genre", models.CharField(default="未知", max_length=200)),
                (
                    "secondary_genre",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("rating", models.FloatField(default=0.0)),
                ("click_nums", models.IntegerField(default=0)),
                ("crawl_time", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
