# Generated by Django 5.0.1 on 2024-02-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appDemo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="novels",
            name="secondary_genre",
            field=models.CharField(default="未知", max_length=200),
        ),
    ]
