# Generated by Django 5.0.1 on 2024-02-18 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appDemo", "0002_alter_novels_secondary_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="NovelsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("word_count", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0.0)),
                ("click_nums", models.IntegerField(default=0)),
                (
                    "novel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="novels_history",
                        to="appDemo.novels",
                    ),
                ),
            ],
            options={
                "unique_together": {("novel", "date")},
            },
        ),
    ]
