# Generated by Django 5.0.1 on 2024-03-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appDemo", "0005_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
